train_data_dir: ./data/raw/adult/adult.data
valid_data_dir: ./data/raw/adult/adult.eval
test_data_dir: ./data/raw/adult/adult.test
train_data_tfrecords_dir: ./data/text/adult/train.tfrecords
test_data_tfrecords_dir: ./data/text/adult/test.tfrecords
load_tf_records_data: True
# traning process config
shuffle: True
model_name: dssm
optimizer: adam
train_epoches_num: 1
batch_size: 16
epoches_per_eval: 2
learning_rate: 0.01
user_dnn_hidden_units:
  - 256
  - 256
  - 128
item_dnn_hidden_units:
  - 256
  - 256
  - 128
user_dnn_dropout:
  - 0
  - 0
  - 0
item_dnn_dropout:
  - 0
  - 0
  - 0
out_dnn_activation: tanh
gamma: 1.2
dnn_use_bn: False
seed: 1024
metric: 'cos'
