train_data_dir: ./data/raw/adult/adult.data
valid_data_dir: ./data/raw/adult/adult.eval
test_data_dir: ./data/raw/adult/adult.test
train_data_tfrecords_dir: ./data/text/adult/train.tfrecords
test_data_tfrecords_dir: ./data/text/adult/test.tfrecords
load_tf_records_data: True
# traning process config
shuffle: True
model_name: deepfm
optimizer: adam
train_epoches_num: 1
batch_size: 16
epoches_per_eval: 2
learning_rate: 0.01
deep_layer_nerouns:
  - 256
  - 128
  - 64
#ckpt_dir: CENSUS_PATH + ckpt_dir/
#embedding_dim: feat_columns[embedding_dim]
#deep_columns: feat_columns[deep_columns]
#deep_fields_size: feat_columns[deep_fields_size]
#wide_columns: feat_columns[wide_columns]
#wide_fields_size: feat_columns[wide_fields_size]
#model_fn_map: MODEL_FN_MAP
fibinet:
  pooling:
    max reduction_ratio: 2